"""Agent-related schemas for MedOS Agentic API layer.

Defines identity, context, events, confidence scoring, and safety
models used across MCP servers, LangGraph agents, and the gateway.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class AgentType(str, Enum):
    """Known agent types in the MedOS platform."""

    CLINICAL_SCRIBE = "clinical_scribe"
    PRIOR_AUTH = "prior_auth"
    DENIAL_MANAGEMENT = "denial_management"
    BILLING = "billing"
    SCHEDULING = "scheduling"
    PATIENT_COMMS = "patient_comms"
    QUALITY_REPORTING = "quality_reporting"
    DEVICE_BRIDGE = "device_bridge"
    SYSTEM = "system"  # internal platform operations


class AgentTaskStatus(str, Enum):
    """Lifecycle status for agent-generated tasks requiring human review."""

    PENDING = "pending"
    IN_REVIEW = "in_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    AUTO_APPROVED = "auto_approved"


class SafetyAction(str, Enum):
    """Actions the safety layer can take on an agent output."""

    BLOCK = "block"
    WARN = "warn"
    REVIEW = "review"
    SANITIZE = "sanitize"
    PASS = "pass"  # noqa: S105


# ---------------------------------------------------------------------------
# Agent Identity & Context
# ---------------------------------------------------------------------------


class AgentContext(BaseModel):
    """Extended identity for agent callers (superset of UserContext).

    Carried through the request lifecycle so MCP tools and middleware
    know *which agent* is calling and *what* it is allowed to access.
    """

    agent_type: AgentType
    agent_version: str = "1.0.0"
    tenant_id: str
    user_id: str = ""  # empty for autonomous agent calls
    session_id: str = ""
    delegation_chain: list[str] = Field(
        default_factory=list,
        description="RFC 8693 'act' claim chain - who delegated to whom",
    )
    purpose_of_use: str = Field(
        default="TREAT",
        description="HIPAA V3 purpose of use: TREAT, HPAYMT, HOPERAT, etc.",
    )
    fhir_scopes: list[str] = Field(
        default_factory=list,
        description="SMART on FHIR scopes granted to this agent",
    )
    encounter_id: str | None = None
    patient_id: str | None = None


# ---------------------------------------------------------------------------
# Confidence Scoring
# ---------------------------------------------------------------------------


class ConfidenceScore(BaseModel):
    """AI output confidence with routing metadata.

    Score < confidence_threshold triggers human review.
    """

    score: float = Field(ge=0.0, le=1.0)
    model_id: str = ""
    prompt_hash: str = ""
    reasoning: str = ""
    requires_review: bool = False

    def check_threshold(self, threshold: float = 0.85) -> bool:
        """Return True if confidence meets threshold."""
        self.requires_review = self.score < threshold
        return not self.requires_review


# ---------------------------------------------------------------------------
# Agent Events
# ---------------------------------------------------------------------------


class AgentEvent(BaseModel):
    """Structured event emitted by agents for audit + event bus."""

    event_type: str  # e.g. "tool.invoked", "resource.accessed", "output.generated"
    agent_type: AgentType
    agent_version: str = "1.0.0"
    tenant_id: str
    session_id: str = ""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    resource_type: str | None = None
    resource_id: str | None = None
    tool_name: str | None = None
    confidence: ConfidenceScore | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# Agent Tasks (Human Review Workflow)
# ---------------------------------------------------------------------------


class AgentTask(BaseModel):
    """A task generated by an agent that may require human review.

    Used for high-stakes operations like claim submission, prior auth,
    and clinical documentation sign-off.
    """

    task_id: str
    agent_type: AgentType
    tenant_id: str
    status: AgentTaskStatus = AgentTaskStatus.PENDING
    title: str
    description: str = ""
    resource_type: str | None = None
    resource_id: str | None = None
    confidence: ConfidenceScore | None = None
    payload: dict[str, Any] = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    reviewed_by: str | None = None
    reviewed_at: datetime | None = None
    review_notes: str = ""


# ---------------------------------------------------------------------------
# Safety Layer
# ---------------------------------------------------------------------------


class SafetyCheckResult(BaseModel):
    """Result of the multi-stage safety pipeline on an agent output."""

    action: SafetyAction
    reason: str = ""
    original_content: str = ""
    sanitized_content: str | None = None
    phi_detected: bool = False
    confidence_below_threshold: bool = False
    checks_passed: list[str] = Field(default_factory=list)
    checks_failed: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# MCP Tool Metadata
# ---------------------------------------------------------------------------


class MCPToolDefinition(BaseModel):
    """Metadata for a registered MCP tool."""

    name: str
    description: str
    server: str  # e.g. "fhir", "scribe", "billing"
    input_schema: dict[str, Any] = Field(default_factory=dict)
    requires_approval: bool = False
    phi_access_level: str = "none"  # none, limited, full
    allowed_agent_types: list[AgentType] = Field(default_factory=list)
